In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')

cat = visa.select_dtypes(include='object').columns
num = visa.select_dtypes(exclude='object').columns

In [12]:
# keys = visa['case_status'].value_counts().keys()
# values = visa['case_status'].value_counts().values

**prevailing wage column**

- count

- mean

- median

- max

- min

- 25p

- 50p

- 75p

- std

In [20]:
# prevailing_wage

np.mean(visa['prevailing_wage'])

74455.81459209183

In [24]:
np.sum(visa['prevailing_wage'])

1897134155.8064997

In [26]:
np.median(visa['prevailing_wage'])

70308.20999999999

In [28]:
np.std(visa['prevailing_wage'])

52814.90589711402

In [30]:
np.max(visa['prevailing_wage'])

319210.27

In [32]:
np.min(visa['prevailing_wage'])

2.1367

In [34]:
np.percentile(visa['prevailing_wage'], 25)

34015.479999999996

In [36]:
np.percentile(visa['prevailing_wage'], 50)

70308.20999999999

In [38]:
np.percentile(visa['prevailing_wage'], 75)

107735.51250000001

In [40]:
count = len(visa['prevailing_wage'])
count

25480

In [42]:
wage = visa['prevailing_wage']
wage

0           592.2029
1         83425.6500
2        122996.8600
3         83434.0300
4        149907.3900
            ...
25475     77092.5700
25476    279174.7900
25477    146298.8500
25478     86154.7700
25479     70876.9100
Name: prevailing_wage, Length: 25480, dtype: float64

In [44]:
np.quantile(visa['prevailing_wage'], 0.25)

34015.479999999996

In [46]:
np.quantile(visa['prevailing_wage'], 0.50)

70308.20999999999

In [48]:
np.quantile(visa['prevailing_wage'], 0.75)

107735.51250000001

In [56]:
count = len(wage)
Min = np.min(wage)
p_25 = np.percentile(wage,25)
mean = np.mean(wage)
median = np.median(wage)
p_50 = np.percentile(wage,50)
p_75 = np.percentile(wage,75)
Max = np.max(wage)
std = np.std(wage)
data = [ count, Min, p_25, mean, median, p_50, p_75, Max, std]
idx = [ 'Count','Min','25P','Mean','Median','50P','75P','Max','Std']
col = ['prevailing_wage']
pd.DataFrame(data, index=idx,columns=col)

        prevailing_wage
Count      25480.000000
Min            2.136700
25P        34015.480000
Mean       74455.814592
Median     70308.210000
50P        70308.210000
75P       107735.512500
Max       319210.270000
Std        52814.905897

In [76]:
l = []
for i in num:
    data = visa[i]
    count = len(data)
    Min = np.min(data)
    p_25 = np.percentile(data,25)
    mean = np.mean(data)
    median = np.median(data)
    p_50 = np.percentile(data,50)
    p_75 = np.percentile(data,75)
    Max = np.max(data)
    std = np.std(data)

    data = [ count, Min, p_25, mean, median, p_50, p_75, Max, std]
    l.append(data)
    
idx = [ 'Count','Min','25P','Mean','Median','50P','75P','Max','Std']
df = pd.DataFrame(l,index=num,columns=idx)
df

,Count,Min,25P,Mean,Median,50P,75P,Max,Std
no_of_employees,25480,-26.0000,1022.00,5667.043210,2109.00,2109.00,3504.0000,602069.00,22877.479904
yr_of_estab,25480,1800.0000,1976.00,1979.409929,1997.00,1997.00,2005.0000,2016.00,42.366098
prevailing_wage,25480,2.1367,34015.48,74455.814592,70308.21,70308.21,107735.5125,319210.27,52814.905897

In [78]:
df.transpose()

        no_of_employees   yr_of_estab  prevailing_wage
Count      25480.000000  25480.000000     25480.000000
Min          -26.000000   1800.000000         2.136700
25P         1022.000000   1976.000000     34015.480000
Mean        5667.043210   1979.409929     74455.814592
Median      2109.000000   1997.000000     70308.210000
50P         2109.000000   1997.000000     70308.210000
75P         3504.000000   2005.000000    107735.512500
Max       602069.000000   2016.000000    319210.270000
Std        22877.479904     42.366098     52814.905897

In [80]:
l = []
for i in num:
    data = visa[i]
    count = len(data)
    Min = np.min(data)
    p_25 = np.percentile(data,25)
    mean = np.mean(data)
    median = np.median(data)
    p_50 = np.percentile(data,50)
    p_75 = np.percentile(data,75)
    Max = np.max(data)
    std = np.std(data)

    data = [ count, Min, p_25, mean, median, p_50, p_75, Max, std]
    l.append(data)
    
idx = [ 'Count','Min','25P','Mean','Median','50P','75P','Max','Std']
df = pd.DataFrame(l,index=num,columns=idx).T
df

        no_of_employees   yr_of_estab  prevailing_wage
Count      25480.000000  25480.000000     25480.000000
Min          -26.000000   1800.000000         2.136700
25P         1022.000000   1976.000000     34015.480000
Mean        5667.043210   1979.409929     74455.814592
Median      2109.000000   1997.000000     70308.210000
50P         2109.000000   1997.000000     70308.210000
75P         3504.000000   2005.000000    107735.512500
Max       602069.000000   2016.000000    319210.270000
Std        22877.479904     42.366098     52814.905897

In [82]:
visa.describe()

       no_of_employees   yr_of_estab  prevailing_wage
count     25480.000000  25480.000000     25480.000000
mean       5667.043210   1979.409929     74455.814592
std       22877.928848     42.366929     52815.942327
min         -26.000000   1800.000000         2.136700
25%        1022.000000   1976.000000     34015.480000
50%        2109.000000   1997.000000     70308.210000
75%        3504.000000   2005.000000    107735.512500
max      602069.000000   2016.000000    319210.270000