**Step 1 : Import the Packages**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step 2 : Create a Dataframe using List**

In [10]:
l = ['Ramesh','Suresh','Satish']
df = pd.DataFrame(l)
df

        0
0  Ramesh
1  Suresh
2  Satish

In [ ]:
pd.DataFrame(data,index,columns)

data : array list
index : array list
columns : array list

In [14]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
df = pd.DataFrame(names,age)
# pd.DataFrame(data,index)
df

         0
20  Ramesh
22  Suresh
24  Satish

**Step 3 : Adding Multiple columns in DataFrame**

In [16]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
df = pd.DataFrame(data=zip(names,age))
# pd.DataFrame(data,index)
df

        0   1
0  Ramesh  20
1  Suresh  22
2  Satish  24

In [18]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
data=zip(names,age)
df = pd.DataFrame(data)
# pd.DataFrame(data,index)
df

        0   1
0  Ramesh  20
1  Suresh  22
2  Satish  24

**Step 4 : Change the index**

In [31]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
data=zip(names,age)
df = pd.DataFrame(data, index = [1,2,3])
df

        0   1
1  Ramesh  20
2  Suresh  22
3  Satish  24

In [35]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
data=zip(names,age)
df = pd.DataFrame(data, index = ["A","B","C"])
df

        0   1
A  Ramesh  20
B  Suresh  22
C  Satish  24

**Step 5 : Change the columns**

In [37]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
data=zip(names,age)
df = pd.DataFrame(data, index = ["A","B","C"], columns=['Names','Age'])
df

    Names  Age
A  Ramesh   20
B  Suresh   22
C  Satish   24

In [41]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
data=zip(names,age)
df = pd.DataFrame(data,["A","B","C"])
df

        0   1
A  Ramesh  20
B  Suresh  22
C  Satish  24

In [43]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
data=zip(names,age)
df = pd.DataFrame(data, ["A","B","C"], ['Names','Age'])
df

    Names  Age
A  Ramesh   20
B  Suresh   22
C  Satish   24

In [45]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
indexes = ["A","B","C"]
cols = ['Names','Age']
data=zip(names,age)
df = pd.DataFrame(data, indexes, cols)
df

    Names  Age
A  Ramesh   20
B  Suresh   22
C  Satish   24

In [51]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
indexes = ["A","B","C"]
cols = ['Names','Age']
data=zip(names,age)
df = pd.DataFrame(data, indexes, cols)
df["City"] = ["Hyd","Mumbai","Pune"]
df

    Names  Age    City
A  Ramesh   20     Hyd
B  Suresh   22  Mumbai
C  Satish   24    Pune

In [58]:
names = ['Ramesh','Suresh','Satish']
age = [20,22,24]
city = ["Hyd","Mumbai","Pune"]
indexes = ["A","B","C"]
cols = ['Names','Age','City']
data=zip(names,age,city)
df = pd.DataFrame(data, indexes, cols)
df

    Names  Age    City
A  Ramesh   20     Hyd
B  Suresh   22  Mumbai
C  Satish   24    Pune

**Step 6 : Already dataframe available, we need to add columns**

In [60]:
df['Marks'] = [35,40,45]
df

    Names  Age    City  Marks
A  Ramesh   20     Hyd     35
B  Suresh   22  Mumbai     40
C  Satish   24    Pune     45

In [63]:
df['Marks'] = [55,60,65]
df

    Names  Age    City  Marks
A  Ramesh   20     Hyd     55
B  Suresh   22  Mumbai     60
C  Satish   24    Pune     65

In [67]:
df['Marks'][1] = 75
df

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_36884/1233284307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Marks'][1] = 75
/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_36884/1233284307.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  df['Marks'][1] = 75

    Names  Age    City  Marks
A  Ramesh   20     Hyd     55
B  Suresh   22  Mumbai     75
C  Satish   24    Pune     65

In [69]:
df

    Names  Age    City  Marks
A  Ramesh   20     Hyd     55
B  Suresh   22  Mumbai     75
C  Satish   24    Pune     65

- For already existed dataframe the above method

    - If column not available it will create a **new column**

    - If column already available it will **update a data**

- Make sure the while creating or updating the values should be equal to **number of rows**

**Step 7 : Create an empty dataframe and update the values**

In [74]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
# SQL and Pandas
# Whatever i'm writing SQL can I able to implement using Pandas
# Banking companies, Finance
# EY Deloitte PWC KPMG
# MAANG

In [80]:
df = pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,22,24]
df['City']=['Hyd','Pune','Blr']
df['Marks']=[100,200,300]
df

    Names  Age  City  Marks
0  Ramesh   20   Hyd    100
1  Suresh   22  Pune    200
2  Satish   24   Blr    300

**Step 8 : Create a dataframe using dictionary**

- **keys** becomes columns
- **values** becomes rows

In [84]:
data = {'Names':['Ramesh','Suresh','Satish'],
       'Age':[20,22,24],
       'City':['Hyd','Pune','Blr'],
       'Marks':[100,200,300]}
df = pd.DataFrame(data)
df

    Names  Age  City  Marks
0  Ramesh   20   Hyd    100
1  Suresh   22  Pune    200
2  Satish   24   Blr    300

In [98]:
data = {'Names':'Ramesh',
       'Age':20,
       'City':'Hyd',
       'Marks':100}
df = pd.DataFrame(data)
df

ValueError: If using all scalar values, you must pass an index

In [96]:
data = {'Names':'Ramesh',
       'Age':20,
       'City':'Hyd',
       'Marks':100}
df = pd.DataFrame(data,index=[1,2])
df

    Names  Age City  Marks
1  Ramesh   20  Hyd    100
2  Ramesh   20  Hyd    100

**Step 9 : Save the DataFrame**

- On what name you want to save the file name
  
- At what location we want to save the directory

    - Same Python location then no need to mention

    - different from python location then need to provide

- Extension of the file

    - .csv (comman separated value)

    - .xlsx (excel sheet)

In [104]:
df.to_csv('data.csv')

**Step 10 : Read the DataFrame**

In [107]:
pd.read_csv('data.csv')

   Unnamed: 0   Names  Age City  Marks
0           1  Ramesh   20  Hyd    100
1           2  Ramesh   20  Hyd    100

In [109]:
df

    Names  Age City  Marks
1  Ramesh   20  Hyd    100
2  Ramesh   20  Hyd    100

In [111]:
df.to_csv('data1.csv',index=False)

In [113]:
pd.read_csv('data1.csv')

    Names  Age City  Marks
0  Ramesh   20  Hyd    100
1  Ramesh   20  Hyd    100

In [115]:
dir(df)

['Age',
 'City',
 'Marks',
 'Names',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']