### Feature Engineering

- So far we have performed feature analysis

    - Data frame quick checks

    - categorical column analysis

    - bar charts, pie charts

    - numerical column analysis

    - histograms, box plots, outliers

    - bi-multi variate analysis

    - correlation, covariance, etc

- Now we need to learn Feature Engineering

    - we will create a new columns for better ML models

    - we will perform the **Encoding** which is to convert categorical to numerical data

    - we will do data **transformations**

    - we will perform **Scaling : Standardization and Normalization**

    - we will perform the **missing value analysis**

- Simply feature engineering means our data will be modified

#### Encoding

- Encoding means convert categorical data to Numerical data

- ML/DL or any models works based on maths

- Models can not understand english characters

- So it is very important convert categorical label to numerical values

- For example Gender column has two lables
    
    - Male
    
    - Female

- Then Female represent as 0, Male represent as 1 based on alphabetical order

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')

cat = visa.select_dtypes(include='object').columns
num = visa.select_dtypes(exclude='object').columns

In [13]:
visa.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [16]:
visa['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

In [20]:
visa['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [ ]:
# number of labels are two
# 0 & 1
# 0 for Certified
# 1 for Denied
# map ==== dict

In [22]:
d = {'Certified':0,"Denied":1}

In [24]:
visa['case_status'].map(d)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [26]:
visa['case_status'] = visa['case_status'].map(d)

In [28]:
visa['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [30]:
visa['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [32]:
c = {'Asia':0,'Africa':1,'North America':2,'Europe':3,'South America':4,'Oceania':5}
visa['continent'] = visa['continent'].map(c)
visa['continent']

0        0
1        0
2        0
3        0
4        1
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: continent, Length: 25480, dtype: int64

In [ ]:
# n = visa['continent'].nunique()
# labels = visa['continent'].unique()
# dict_con = {labels[i] : i for i in range(len(labels)) }
# visa['continent'] = visa['continent'].map(dict_con)

In [ ]:
# labels = visa['continent'].unique()
# d = {}
# for i in range(len(labels)):
#     d[labels[i]]=i
# d

In [34]:
visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')
cat = visa.select_dtypes(include='object').columns
num = visa.select_dtypes(exclude='object').columns

for col in cat:
    n = visa[col].nunique()
    labels = visa[col].unique()
    dict_con = {labels[i] : i for i in range(len(labels)) }
    visa[col] = visa[col].map(dict_con)

visa

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,1,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,2,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,3,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,4,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,25475,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,25476,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,25477,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,25478,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,25479,0,2,1,0,3195,1960,3,70876.9100,1,0,1

In [36]:
visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')
cat = visa.select_dtypes(include='object').columns
num = visa.select_dtypes(exclude='object').columns

for col in cat[1:]:
    n = visa[col].nunique()
    labels = visa[col].unique()
    dict_con = {labels[i] : i for i in range(len(labels)) }
    visa[col] = visa[col].map(dict_con)

visa

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')

cat = visa.select_dtypes(include='object').columns
num = visa.select_dtypes(exclude='object').columns

In [ ]:
# visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')
# cat = visa.select_dtypes(include='object').columns
# num = visa.select_dtypes(exclude='object').columns

# for col in cat[1:]:
#     n = visa[col].nunique()
#     labels = visa[col].unique()
#     dict_con = {labels[i] : i for i in range(len(labels)) }
#     visa[col] = visa[col].map(dict_con)

# visa

- we have encoded categorical data to numerical data using scratch

- but the same way we have a **Package**

- Name of Package is : **scikit-learn** aka sklearn

- it is a heart of ML

- 99% of all ML are under Sklearn package

- Package : sklearn

    - Module name : preprocessing

        - Class : LabelEncoder
     
            - Method :
     
                      - fit
                      - transform
                      - fit_transform

- while doing the  encoding

    - we created the dictionary

    - we use the dictionary on original data, the data become Encoded

    - The **Data Changed**
 
- **Create** and **Modify**

- **Create** means : **fit** and **Modify** means : **transform**

In [ ]:
from sklearn.preprocessing import LabelEncoder

# from sklearn.<module> import <class>

In [13]:
import sklearn

dir(sklearn)

['_BUILT_WITH_MESON',
 '__SKLEARN_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__check_build',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_distributor_init',
 'base',
 'clone',
 'config_context',
 'exceptions',
 'externals',
 'get_config',
 'logger',
 'logging',
 'os',
 'preprocessing',
 'random',
 'set_config',
 'setup_module',
 'show_versions',
 'sklearn',
 'sys',
 'utils']

In [ ]:
import sklearn

dir(sklearn)

from sklearn import preprocessing 

dir(preprocessing)

from sklearn.preprocessing import LabelEncoder

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

visa['case_status'] = le.fit_transform(visa['case_status'])

In [19]:
visa['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [21]:
visa

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [28]:
from sklearn.preprocessing import LabelEncoder

visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')

cat = visa.select_dtypes(include='object').columns
num = visa.select_dtypes(exclude='object').columns

le = LabelEncoder() 

for i in cat[1:]:
    
    visa[i] = le.fit_transform(visa[i])

visa

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [30]:
le.inverse_transform(visa['case_status'])

array(['Denied', 'Certified', 'Denied', ..., 'Certified', 'Certified',
       'Certified'], dtype=object)

In [34]:
visa

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [48]:
le.fit_transform(visa['continent'])[:10]

array([1, 1, 1, 1, 0, 1, 1, 3, 1, 2])

In [52]:
visa['continent'].values

array([1, 1, 1, ..., 1, 1, 1])

In [66]:
d = le.fit_transform(visa['continent'])

le.inverse_transform(d)

array([1, 1, 1, ..., 1, 1, 1])

OneHotEncoder
------

- one hot encoder means at a time one will be **ON**, another will be **OFF**

- First how many labels are there in a column

- That many new columns will be created extra

- For example case status has two labels

    - Certified

    - Denied

- So It will create Two new extra columns

    - case_status_Certified

    - case_status_Denied

- At a time one column value become 1 other column value become 0

- This means a **one hot encoder**

|case_status|case_status_Certified|case_status_Denied|
|-|-|-|
|Certified|1|0|
|Denied|0|1|
|Denied|0|1|
|Certified|1|0|

In [68]:
visa.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [ ]:
# understand the patterns between input and output columns

we do not want relation between two inputs
        |
the two columns should be independent 
        |
perpendicular
        |
90 degrees Phase shift
        |
cos and sin 90
        |
cos 90 = sin 0
sin 0 = cos 90
        |
orthogonality

1 ==== 0


Curse of Dimensionality :- more labels -> more dimensions -> more process the data -> more time and more money 

Relationships :- 

- x1 with x1 -> auto correlation

- x1 with x2 -> multi collinearity

- x1 with y -> correlation