In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [4]:
d = {'Names':['Ramesh','Suresh','Satish','Mahesh'],
     'Age':[20,22,24,26],
     'City':['Hyd','Blr','Pune','Mumbai']
    }

df = pd.DataFrame(d)

df

    Names  Age    City
0  Ramesh   20     Hyd
1  Suresh   22     Blr
2  Satish   24    Pune
3  Mahesh   26  Mumbai

**How to create a Null values in a data**

- None
  
- np.nan

In [7]:
d1 = {'Names':['Ramesh','Suresh',None,'Mahesh'],
     'Age':[20,22,24,None],
     'City':[None,'Blr','Pune','Mumbai']
    }

df1 = pd.DataFrame(d1)

df1

    Names   Age    City
0  Ramesh  20.0    None
1  Suresh  22.0     Blr
2    None  24.0    Pune
3  Mahesh   NaN  Mumbai

- Even though we provided None, the numerical column value by default **NaN**

- Categorical column value takes a **None**

In [10]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [12]:
df1.isnull()

   Names    Age   City
0  False  False   True
1  False  False  False
2   True  False  False
3  False   True  False

In [14]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [16]:
df1.to_csv('df1.csv',index=False)

In [18]:
d2 = {'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
     'Age':[20,22,24,np.nan],
     'City':[np.nan,'Blr','Pune','Mumbai']
    }

df2 = pd.DataFrame(d2)

df2

    Names   Age    City
0  Ramesh  20.0     NaN
1  Suresh  22.0     Blr
2     NaN  24.0    Pune
3  Mahesh   NaN  Mumbai

In [22]:
df2.dtypes

Names     object
Age      float64
City      object
dtype: object

In [24]:
df2.isnull()

   Names    Age   City
0  False  False   True
1  False  False  False
2   True  False  False
3  False   True  False

In [26]:
df2.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [28]:
df2.to_csv('df2.csv',index=False)

**None vs np.nan**

In [31]:
arr1 = np.array([100,200,None])
arr2 = np.array([100,200,np.nan])

In [33]:
sum(arr1)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [35]:
sum(arr2)

nan

In [37]:
100+None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [41]:
100+np.nan

nan

In [47]:
np.sum(arr2) # 100 + 200 + nan

nan

In [49]:
np.nansum(arr2) # 100 + 200

300.0

In [51]:
arr3 = np.array([10,20,'30',40])
arr3

array(['10', '20', '30', '40'], dtype='<U21')

In [53]:
arr4 = np.array([10,20,'30+',40])
arr4

array(['10', '20', '30+', '40'], dtype='<U21')

In [55]:
arr5 = np.array([10,20,'thirty',40])
arr5

array(['10', '20', 'thirty', '40'], dtype='<U21')

In [68]:
arr3 = np.array([10,20,'30',40])
arr3.astype(int)

array([10, 20, 30, 40])

In [66]:
arr3 = np.array([10,20,'30',40])
arr3.astype(int).dtype

dtype('int64')

**fill with random value**

In [72]:
df1.fillna(100)

    Names    Age    City
0  Ramesh   20.0     100
1  Suresh   22.0     Blr
2     100   24.0    Pune
3  Mahesh  100.0  Mumbai

In [74]:
df1

    Names   Age    City
0  Ramesh  20.0    None
1  Suresh  22.0     Blr
2    None  24.0    Pune
3  Mahesh   NaN  Mumbai

**fill the random value based on specific column**

In [77]:
df1['Age'].fillna(30)

0    20.0
1    22.0
2    24.0
3    30.0
Name: Age, dtype: float64

- Mean

- Median

- Mode

In [80]:
mean_value = df1['Age'].mean()
df1['Age'].fillna(mean_value)

0    20.0
1    22.0
2    24.0
3    22.0
Name: Age, dtype: float64

In [85]:
df1['City'].mode()

0       Blr
1    Mumbai
2      Pune
Name: City, dtype: object

In [87]:
n = len(df1)
df1.loc[n]=['Anish',np.nan,'Pune']

In [89]:
df1

    Names   Age    City
0  Ramesh  20.0    None
1  Suresh  22.0     Blr
2    None  24.0    Pune
3  Mahesh   NaN  Mumbai
4   Anish   NaN    Pune

In [95]:
df1['City'].mode() # series

0    Pune
Name: City, dtype: object

In [97]:
df1['Age'].mean() # scalar

22.0

In [99]:
mean_value = df1['Age'].mean()
df1['Age'].fillna(mean_value)

0    20.0
1    22.0
2    24.0
3    22.0
4    22.0
Name: Age, dtype: float64

In [101]:
mode_value = df1['City'].mode()
df1['City'].fillna(mode_value)

0      Pune
1       Blr
2      Pune
3    Mumbai
4      Pune
Name: City, dtype: object

In [103]:
mode_value[0]

'Pune'

In [107]:
mode_value = df1['City'].mode()
mode_value[0]

df1['City'].fillna(mode_value[0])

0      Pune
1       Blr
2      Pune
3    Mumbai
4      Pune
Name: City, dtype: object

**methods**

- method argument

    - bfill
    
    - ffill
    
    - pad
    
    - backfill
 
- it will fill the values automatically

In [111]:
df1

    Names   Age    City
0  Ramesh  20.0    None
1  Suresh  22.0     Blr
2    None  24.0    Pune
3  Mahesh   NaN  Mumbai
4   Anish   NaN    Pune

In [113]:
df1.fillna(method='bfill')

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_59966/2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

    Names   Age    City
0  Ramesh  20.0     Blr
1  Suresh  22.0     Blr
2  Mahesh  24.0    Pune
3  Mahesh   NaN  Mumbai
4   Anish   NaN    Pune

In [119]:
df1.fillna(method='ffill')

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_59966/598575452.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')

    Names   Age    City
0  Ramesh  20.0    None
1  Suresh  22.0     Blr
2  Suresh  24.0    Pune
3  Mahesh  24.0  Mumbai
4   Anish  24.0    Pune

In [121]:
df1.fillna(method='pad')

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_59966/3887010614.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

    Names   Age    City
0  Ramesh  20.0    None
1  Suresh  22.0     Blr
2  Suresh  24.0    Pune
3  Mahesh  24.0  Mumbai
4   Anish  24.0    Pune

In [123]:
df1.fillna(method='backfill')

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_59966/2955370104.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='backfill')

    Names   Age    City
0  Ramesh  20.0     Blr
1  Suresh  22.0     Blr
2  Mahesh  24.0    Pune
3  Mahesh   NaN  Mumbai
4   Anish   NaN    Pune

In [125]:
d2 = {
    'Name':['R','A','M','S','L'],
    'Department':['E','E','C','C','E'],
    'Salary':[7,8,5,5,np.nan]
}

df3 = pd.DataFrame(d2)

df3

  Name Department  Salary
0    R          E     7.0
1    A          E     8.0
2    M          C     5.0
3    S          C     5.0
4    L          E     NaN

In [129]:
df3.groupby('Department')['Salary'].mean()

Department
C    5.0
E    7.5
Name: Salary, dtype: float64

In [131]:
con = df3['Department']=='E'

df3.groupby(con)['Salary'].mean()

Department
False    5.0
True     7.5
Name: Salary, dtype: float64

In [135]:
df3['Salary'].fillna(7.5)

0    7.0
1    8.0
2    5.0
3    5.0
4    7.5
Name: Salary, dtype: float64

In [140]:
df3

  Name Department  Salary
0    R          E     7.0
1    A          E     8.0
2    M          C     5.0
3    S          C     5.0
4    L          E     NaN

In [142]:
df3.fillna(7.5)

  Name Department  Salary
0    R          E     7.0
1    A          E     8.0
2    M          C     5.0
3    S          C     5.0
4    L          E     7.5