In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
os.getcwd()

'/Users/pranay/Naresh IT/Python/EDA'

In [3]:
bank = pd.read_csv('/Users/pranay/Naresh IT/Data Files/bank.csv')

In [4]:
bank.head()

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  30;"unemployed";"married";"primary";"no";1787;...
1  33;"services";"married";"secondary";"no";4789;...
2  35;"management";"single";"tertiary";"no";1350;...
3  30;"management";"married";"tertiary";"no";1476...
4  59;"blue-collar";"married";"secondary";"no";0;...

In [5]:
visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')

In [6]:
visa.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [7]:
bank = pd.read_csv('/Users/pranay/Naresh IT/Data Files/bank.csv',sep=';')
bank.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [8]:
bank

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [9]:
visa.shape

(25480, 12)

In [10]:
visa.size

305760

In [11]:
visa.head(5)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [12]:
visa.tail(5)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [13]:
visa.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [14]:
visa.info

<bound method DataFrame.info of          case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N
1         EZYV02      Asia              Master's                  Y
2         EZYV03      Asia            Bachelor's                  N
3         EZYV04      Asia            Bachelor's                  N
4         EZYV05    Africa              Master's                  Y
...          ...       ...                   ...                ...
25475  EZYV25476      Asia            Bachelor's                  Y
25476  EZYV25477      Asia           High School                  Y
25477  EZYV25478      Asia              Master's                  Y
25478  EZYV25479      Asia              Master's                  Y
25479  EZYV25480      Asia            Bachelor's                  Y

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007
1                         N             2412         2002
2                         Y            44444         2008
3                         N               98         1897
4                         N             1082         2005
...                     ...              ...          ...
25475                     Y             2601         2008
25476                     N             3274         2006
25477                     N             1121         1910
25478                     Y             1918         1887
25479                     N             3195         1960

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y
1                Northeast       83425.6500         Year                  Y
2                     West      122996.8600         Year                  Y
3                     West       83434.0300         Year                  Y
4                    South      149907.3900         Year                  Y
...                    ...              ...          ...                ...
25475                South       77092.5700         Year                  Y
25476            Northeast      279174.7900         Year                  Y
25477                South      146298.8500         Year                  N
25478                 West       86154.7700         Year                  Y
25479              Midwest       70876.9100         Year                  Y

      case_status
0          Denied
1       Certified
2          Denied
3          Denied
4       Certified
...           ...
25475   Certified
25476   Certified
25477   Certified
25478   Certified
25479   Certified

[25480 rows x 12 columns]>

In [15]:
visa.isnull

<bound method DataFrame.isnull of          case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N
1         EZYV02      Asia              Master's                  Y
2         EZYV03      Asia            Bachelor's                  N
3         EZYV04      Asia            Bachelor's                  N
4         EZYV05    Africa              Master's                  Y
...          ...       ...                   ...                ...
25475  EZYV25476      Asia            Bachelor's                  Y
25476  EZYV25477      Asia           High School                  Y
25477  EZYV25478      Asia              Master's                  Y
25478  EZYV25479      Asia              Master's                  Y
25479  EZYV25480      Asia            Bachelor's                  Y

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007
1                         N             2412         2002
2                         Y            44444         2008
3                         N               98         1897
4                         N             1082         2005
...                     ...              ...          ...
25475                     Y             2601         2008
25476                     N             3274         2006
25477                     N             1121         1910
25478                     Y             1918         1887
25479                     N             3195         1960

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y
1                Northeast       83425.6500         Year                  Y
2                     West      122996.8600         Year                  Y
3                     West       83434.0300         Year                  Y
4                    South      149907.3900         Year                  Y
...                    ...              ...          ...                ...
25475                South       77092.5700         Year                  Y
25476            Northeast      279174.7900         Year                  Y
25477                South      146298.8500         Year                  N
25478                 West       86154.7700         Year                  Y
25479              Midwest       70876.9100         Year                  Y

      case_status
0          Denied
1       Certified
2          Denied
3          Denied
4       Certified
...           ...
25475   Certified
25476   Certified
25477   Certified
25478   Certified
25479   Certified

[25480 rows x 12 columns]>

In [16]:
visa.isnull()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,False,False,False,False,False,False,False,False,False,False,False,False
25476,False,False,False,False,False,False,False,False,False,False,False,False
25477,False,False,False,False,False,False,False,False,False,False,False,False
25478,False,False,False,False,False,False,False,False,False,False,False,False
25479,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
visa.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [18]:
type(visa)

pandas.core.frame.DataFrame

In [19]:
type(visa.columns)

pandas.core.indexes.base.Index

In [20]:
cols = visa.columns
cols

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [21]:
cols.index('continent')

AttributeError: 'Index' object has no attribute 'index'

In [34]:
l = ['a','b','c']
l.index('b')

1

In [35]:
cols = visa.columns.to_list()
cols.index('continent')

1

**loc and iloc**

In [71]:
# visa.iloc[<rows>,<columns>]

# l[start:stop:step]

# visa.iloc[start:stop:step , start:stop:step]

In [73]:
visa.iloc[100:105,3:7]
# columns index 3 to 6
# rows 100 to 104

    has_job_experience requires_job_training  no_of_employees  yr_of_estab
100                  Y                     N             2227         2007
101                  Y                     N              334         2007
102                  Y                     N              224         2008
103                  Y                     N              367         1982
104                  Y                     N              306         2003

In [74]:
visa.iloc[100]
# series data

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [75]:
visa.iloc[[100]]
# dataframe data

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified

In [76]:
visa.iloc[[100,200]]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified

- **Series and Dataframe** look like both are same but not same

- Series is a **1D data**

- Series is like a **key-value pair**

- Dataframe is a **2D data**

- If you want to select **multiple values** always **provide in a list**

In [78]:
visa.iloc[100].keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [79]:
visa.iloc[100].values

array(['EZYV101', 'Asia', "Master's", 'Y', 'N', 2227, 2007, 'Northeast',
       28243.79, 'Year', 'Y', 'Certified'], dtype=object)

In [80]:
visa.iloc[100].keys()
visa.iloc[100].index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [81]:
pd.DataFrame(visa.iloc[100])

                             100
case_id                  EZYV101
continent                   Asia
education_of_employee   Master's
has_job_experience             Y
requires_job_training          N
no_of_employees             2227
yr_of_estab                 2007
region_of_employment   Northeast
prevailing_wage         28243.79
unit_of_wage                Year
full_time_position             Y
case_status            Certified

In [82]:
dict(visa.iloc[100])

{'case_id': 'EZYV101',
 'continent': 'Asia',
 'education_of_employee': "Master's",
 'has_job_experience': 'Y',
 'requires_job_training': 'N',
 'no_of_employees': 2227,
 'yr_of_estab': 2007,
 'region_of_employment': 'Northeast',
 'prevailing_wage': 28243.79,
 'unit_of_wage': 'Year',
 'full_time_position': 'Y',
 'case_status': 'Certified'}

In [83]:
pd.DataFrame(visa.iloc[[100,200]])

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified

In [84]:
visa.iloc[[100,200,300],[3,6,9]]

    has_job_experience  yr_of_estab unit_of_wage
100                  Y         2007         Year
200                  Y         1979         Year
300                  Y         2012         Year

In [85]:
visa.iloc[[100,200,300],]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [86]:
visa.iloc[[100,200,300],:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [87]:
visa.iloc[:,[3,6,9]]

      has_job_experience  yr_of_estab unit_of_wage
0                      N         2007         Hour
1                      Y         2002         Year
2                      N         2008         Year
3                      N         1897         Year
4                      Y         2005         Year
...                  ...          ...          ...
25475                  Y         2008         Year
25476                  Y         2006         Year
25477                  Y         1910         Year
25478                  Y         1887         Year
25479                  Y         1960         Year

[25480 rows x 3 columns]

In [88]:
visa.iloc[:,:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [89]:
visa.iloc[:,3]

0        N
1        Y
2        N
3        N
4        Y
        ..
25475    Y
25476    Y
25477    Y
25478    Y
25479    Y
Name: has_job_experience, Length: 25480, dtype: object

In [90]:
visa.iloc[:,[3]]

      has_job_experience
0                      N
1                      Y
2                      N
3                      N
4                      Y
...                  ...
25475                  Y
25476                  Y
25477                  Y
25478                  Y
25479                  Y

[25480 rows x 1 columns]

In [91]:
visa[:,1]

InvalidIndexError: (slice(None, None, None), 1)

In [92]:
visa[:,[1]]

InvalidIndexError: (slice(None, None, None), [1])

In [94]:
visa[100]

KeyError: 100

In [96]:
visa.values

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      dtype=object)

In [98]:
visa.values[100]

array(['EZYV101', 'Asia', "Master's", 'Y', 'N', 2227, 2007, 'Northeast',
       28243.79, 'Year', 'Y', 'Certified'], dtype=object)

**DataFrames to Values**

In [100]:
visa.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [101]:
visa.loc[[100,200,300],['continent','unit_of_wage']]

    continent unit_of_wage
100      Asia         Year
200      Asia         Year
300      Asia         Year

In [102]:
visa.loc[:,['continent','unit_of_wage']]

      continent unit_of_wage
0          Asia         Hour
1          Asia         Year
2          Asia         Year
3          Asia         Year
4        Africa         Year
...         ...          ...
25475      Asia         Year
25476      Asia         Year
25477      Asia         Year
25478      Asia         Year
25479      Asia         Year

[25480 rows x 2 columns]

In [103]:
visa.loc[:,:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [104]:
visa.loc[[100],['continent','unit_of_wage']]

    continent unit_of_wage
100      Asia         Year

In [105]:
visa.loc[[1,2,3],['continent','unit_of_wage','education_of_employee']]

  continent unit_of_wage education_of_employee
1      Asia         Year              Master's
2      Asia         Year            Bachelor's
3      Asia         Year            Bachelor's

In [106]:
visa.loc[100]

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [107]:
visa.loc[[100]]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified

In [108]:
visa.loc[[100,200],'continent':'yr_of_estab']

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab
100,Asia,Master's,Y,N,2227,2007
200,Asia,Doctorate,Y,N,3282,1979

In [109]:
visa.loc[101:105,'continent':'yr_of_estab']

,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab
101,Asia,Master's,Y,N,334,2007
102,Asia,Bachelor's,Y,N,224,2008
103,Asia,Doctorate,Y,N,367,1982
104,Asia,Master's,Y,N,306,2003
105,North America,Doctorate,Y,N,2317,1995

In [110]:
visa.loc[101:105,:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
101,EZYV102,Asia,Master's,Y,N,334,2007,Midwest,43421.88,Year,Y,Certified
102,EZYV103,Asia,Bachelor's,Y,N,224,2008,Midwest,80253.78,Year,Y,Certified
103,EZYV104,Asia,Doctorate,Y,N,367,1982,West,115235.95,Year,Y,Certified
104,EZYV105,Asia,Master's,Y,N,306,2003,Northeast,95200.86,Year,N,Certified
105,EZYV106,North America,Doctorate,Y,N,2317,1995,Island,41613.52,Year,Y,Certified

In [111]:
visa.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

**Dtypes**

In [130]:
visa.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

- object indicates Categorical column

- dtypes gives series operations

In [133]:
visa.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [135]:
visa.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [137]:
visa.dtypes.index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [139]:
cols = visa.dtypes.index
cols

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [143]:
values = visa.dtypes.values
values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [145]:
cols = visa.dtypes.keys()
cols

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [147]:
pd.DataFrame(zip(cols,values),columns=['Columns','Data Type'])

                  Columns Data Type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [149]:
cols = visa.dtypes.index
values = visa.dtypes.values
pd.DataFrame(zip(cols,values),columns=['Columns','Data Type'])

                  Columns Data Type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [151]:
visa
dtypes = visa.dtypes
pd.DataFrame(dtypes)
df = pd.DataFrame(dtypes).reset_index()
df.columns
df.columns = ['Column Name','Data Type']
df

              Column Name Data Type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [153]:
df = pd.DataFrame(visa.dtypes).reset_index()
df.columns = ['Column Name','Data Types']
df

              Column Name Data Types
0                 case_id     object
1               continent     object
2   education_of_employee     object
3      has_job_experience     object
4   requires_job_training     object
5         no_of_employees      int64
6             yr_of_estab      int64
7    region_of_employment     object
8         prevailing_wage    float64
9            unit_of_wage     object
10     full_time_position     object
11            case_status     object

In [155]:
visa.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [167]:
cols = visa.dtypes.keys().tolist()
data_types = visa.dtypes.values.tolist()
cat = [i for i,j in zip(cols,data_types) if j=='object']
num = [i for i,j in zip(cols,data_types) if j!='object']
# for i,j in zip(cols,data_types):
#     if j=='object':
#         print(i)
print(cat)
print()
print(num)

['case_id', 'continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'region_of_employment', 'unit_of_wage', 'full_time_position', 'case_status']

['no_of_employees', 'yr_of_estab', 'prevailing_wage']

**select dtypes**

In [172]:
cat = visa.select_dtypes(include='object').columns
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [174]:
num = visa.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [176]:
visa['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [178]:
visa[['continent']]

      continent
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
...         ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia

[25480 rows x 1 columns]

In [180]:
visa.continent

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [182]:
visa.iloc[:,1]

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [184]:
visa.iloc[:,[1]]

      continent
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
...         ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia

[25480 rows x 1 columns]

In [186]:
visa.loc[:,'continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [188]:
visa.loc[:,['continent']]

      continent
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
...         ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia

[25480 rows x 1 columns]

In [190]:
visa['continent','case_status'] # wrong

KeyError: ('continent', 'case_status')

In [192]:
visa[['continent','case_status']] # correct

      continent case_status
0          Asia      Denied
1          Asia   Certified
2          Asia      Denied
3          Asia      Denied
4        Africa   Certified
...         ...         ...
25475      Asia   Certified
25476      Asia   Certified
25477      Asia   Certified
25478      Asia   Certified
25479      Asia   Certified

[25480 rows x 2 columns]

**continent column**

In [195]:
visa['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

**unique**

In [198]:
visa['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

**nunique**

In [200]:
visa['continent'].nunique()

6

**raw data**

In [203]:
visa['continent'].values

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'], dtype=object)

In [206]:
visa

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [214]:
visa
visa['continent']
visa['continent'] == 'Asia'
con = visa['continent'] == 'Asia'
visa[con]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
5,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.1400,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [216]:
len(visa[con])

16861

In [255]:
# con = visa['continent'] == 'Asia'
# len(visa[con])

# con = visa['continent'] == i

labels = visa['continent'].unique()
count = []
for i in labels:
    con = visa['continent'] == i
    count.append(len(visa[con]))
print(labels)
print(count)

['Asia' 'Africa' 'North America' 'Europe' 'South America' 'Oceania']
[16861, 551, 3292, 3732, 852, 192]

In [259]:
# cont = visa['continent'].unique()
# for i in cont:
#     con = visa['continent']== i
#     count = len(visa[con])
#     print(i,'=',count)

In [257]:
continent = pd.DataFrame(zip(labels,count), columns=['Continent','No of Applicants'])
continent

       Continent  No of Applicants
0           Asia             16861
1         Africa               551
2  North America              3292
3         Europe              3732
4  South America               852
5        Oceania               192

**value counts**

In [250]:
visa['continent'].value_counts()

continent
Asia             16861
Europe            3732
North America     3292
South America      852
Africa             551
Oceania            192
Name: count, dtype: int64

In [267]:
keys = visa['continent'].value_counts().keys()
values = visa['continent'].value_counts().values
conti = pd.DataFrame(zip(keys,values),columns=['Continent','No of Applicants'])
conti

       Continent  No of Applicants
0           Asia             16861
1         Europe              3732
2  North America              3292
3  South America               852
4         Africa               551
5        Oceania               192

**group by**

- Divide the continent into groups

- there are 6 continents so 6 groups

- then calculate each size

In [271]:
visa.groupby('continent').size()

continent
Africa             551
Asia             16861
Europe            3732
North America     3292
Oceania            192
South America      852
dtype: int64

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
visa = pd.read_csv('/Users/pranay/Naresh IT/Data Files/Visadataset.csv')

In [3]:
visa.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [7]:
visa.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [9]:
cat = visa.select_dtypes(include='object').columns
num = visa.select_dtypes(exclude='object').columns

In [11]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [13]:
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

- Task 1 : Education of employee using frequency table using conditions

- Task 2 : Education of employee using frequency table using value counts

- Task 3 : Education of employee using frequency table using groupby

- Task 4 : Create a new directory called frequency table and save the freq table of Educaton of employee value counts tasks

In [16]:
labels = visa['continent'].unique()
count = []
for i in labels:
    con = visa['continent'] == i
    count.append(len(visa[con]))
print(labels)
print(count)

['Asia' 'Africa' 'North America' 'Europe' 'South America' 'Oceania']
[16861, 551, 3292, 3732, 852, 192]

In [18]:
keys = visa['continent'].value_counts().keys()
values = visa['continent'].value_counts().values
conti = pd.DataFrame(zip(keys,values),columns=['Continent','No of Applicants'])
conti

       Continent  No of Applicants
0           Asia             16861
1         Europe              3732
2  North America              3292
3  South America               852
4         Africa               551
5        Oceania               192

In [20]:
visa.groupby('continent').size()

continent
Africa             551
Asia             16861
Europe            3732
North America     3292
Oceania            192
South America      852
dtype: int64

In [24]:
keys = visa['education_of_employee'].value_counts().keys()
values = visa['education_of_employee'].value_counts().values
d = pd.DataFrame(zip(keys,values),columns=['Lables','No of Applicants'])
d.to_csv('education_of_employee.csv', index=False)

In [26]:
import os

os.makedirs('frequency_table',exist_ok=True)
# d.to_csv(<>,index=False)

In [28]:
os.getcwd()

'/Users/pranay/Naresh IT/Python/EDA'

In [32]:
path = r'/Users/pranay/Naresh IT/Python/EDA/frequency_table/education_of_employee.csv'
os.makedirs('frequency_table',exist_ok=True)

In [34]:
cwd = os.getcwd()
cwd

'/Users/pranay/Naresh IT/Python/EDA'

In [36]:
new_folder = os.makedirs('freq_table',exist_ok=True)

In [38]:
os.path.join(cwd,new_folder)

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

In [42]:
cwd = os.getcwd()
cwd
folder_name = 'freq_table'
new_folder = os.makedirs(folder_name,exist_ok=True)
new_dir = os.path.join(cwd,folder_name)
new_dir

'/Users/pranay/Naresh IT/Python/EDA/freq_table'

In [44]:
col_name = 'education_of_employee'
file_path = os.path.join(new_dir,f"{col_name}.csv")
file_path

'/Users/pranay/Naresh IT/Python/EDA/freq_table/education_of_employee.csv'

In [46]:
for i in cat:
    cwd = os.getcwd()
    folder_name = 'freq_table_1'
    new_folder = os.makedirs(folder_name,exist_ok=True)
    new_dir = os.path.join(cwd,folder_name)
    col_name = i
    file_path = os.path.join(new_dir,f"{i}.csv")
    print(file_path)

/Users/pranay/Naresh IT/Python/EDA/freq_table_1/case_id.csv
/Users/pranay/Naresh IT/Python/EDA/freq_table_1/continent.csv
/Users/pranay/Naresh IT/Python/EDA/freq_table_1/education_of_employee.csv
/Users/pranay/Naresh IT/Python/EDA/freq_table_1/has_job_experience.csv
/Users/pranay/Naresh IT/Python/EDA/freq_table_1/requires_job_training.csv
/Users/pranay/Naresh IT/Python/EDA/freq_table_1/region_of_employment.csv
/Users/pranay/Naresh IT/Python/EDA/freq_table_1/unit_of_wage.csv
/Users/pranay/Naresh IT/Python/EDA/freq_table_1/full_time_position.csv
/Users/pranay/Naresh IT/Python/EDA/freq_table_1/case_status.csv

In [50]:
for i in cat[1:]:
    keys = visa[i].value_counts().keys()
    values = visa[i].value_counts().values
    d = pd.DataFrame(zip(keys,values),columns=['Lables','No of Applicants'])
    print(d)

          Lables  No of Applicants
0           Asia             16861
1         Europe              3732
2  North America              3292
3  South America               852
4         Africa               551
5        Oceania               192
        Lables  No of Applicants
0   Bachelor's             10234
1     Master's              9634
2  High School              3420
3    Doctorate              2192
  Lables  No of Applicants
0      Y             14802
1      N             10678
  Lables  No of Applicants
0      N             22525
1      Y              2955
      Lables  No of Applicants
0  Northeast              7195
1      South              7017
2       West              6586
3    Midwest              4307
4     Island               375
  Lables  No of Applicants
0   Year             22962
1   Hour              2157
2   Week               272
3  Month                89
  Lables  No of Applicants
0      Y             22773
1      N              2707
      Lables  No of Applicants
0  Certified             17018
1     Denied              8462

In [52]:
keys = visa['education_of_employee'].value_counts().keys()
values = visa['education_of_employee'].value_counts().values
d = pd.DataFrame(zip(keys,values),columns=['Lables','No of Applicants'])
d

        Lables  No of Applicants
0   Bachelor's             10234
1     Master's              9634
2  High School              3420
3    Doctorate              2192

In [54]:
os.getcwd()

'/Users/pranay/Naresh IT/Python/EDA'

In [60]:
for i in cat[1:]:
    keys = visa[i].value_counts().keys()
    values = visa[i].value_counts().values
    d = pd.DataFrame(zip(keys,values),columns=['Lables','No of Applicants'])

    cwd = os.getcwd()
    folder_name = 'freq'
    os.makedirs(folder_name,exist_ok=True)
    new_dir = os.path.join(cwd,folder_name)
    path = os.path.join(new_dir,f"{i}.csv")
    
    d.to_csv(path,index=False)

In [66]:
visa.groupby('education_of_employee').size()

education_of_employee
Bachelor's     10234
Doctorate       2192
High School     3420
Master's        9634
dtype: int64